#!/bin/bash

#create frontend service account
gcloud iam --project=testproject123-cram service-accounts create cram-frontend-service \
    --description="Frontend Service Account" \
    --display-name="cram-frontend-service"

#create backend service account
gcloud iam --project=testproject123-cram service-accounts create cram-backend-service \
    --description="Backend Service Account" \
    --display-name="cram-backend-service"

#create vpc network
gcloud compute networks create ccl1-network \
    --project=testproject123-cram \
    --subnet-mode=custom \
    --bgp-routing-mode=regional

#create vpc frontend subnet
gcloud compute networks subnets create frontend-subnet \
    --project=testproject123-cram \
    --range=192.168.0.0/24 \
    --network=ccl1-network \
    --region=us-east1


#create vpc backend subnet
gcloud compute networks subnets create backend-subnet \
    --project=testproject123-cram \
    --range=192.168.1.0/24 \
    --network=ccl1-network \
    --region=us-west1

#Firewall Rule Frontend Outbound Ping
gcloud compute --project=testproject123-cram firewall-rules create frontend-outbound-icmp \
    --direction=EGRESS \
    --priority=1000 \
    --network=ccl1-network \ 
    --action=ALLOW \
    --rules=icmp \
    --destination-ranges=0.0.0.0/0 \ 
    --target-service-accounts=cram-frontend-service@testproject123-cram.iam.gserviceaccount.com

#firewall Rule Frontend Inbound PING from FrontEnd SA
gcloud compute --project=testproject123-cram firewall-rules create f-frontend-inbound-icmp \
    --direction=INGRESS \
    --priority=1000 \
    --network=ccl1-network \
    --action=ALLOW \
    --rules=icmp \
    --source-ranges=0.0.0.0/0 \
    --target-service-accounts=cram-frontend-service@testproject123-cram.iam.gserviceaccount.com

#firewall Rule Frontend Inbound PING from BackEnd SA
gcloud compute --project=testproject123-cram firewall-rules create b-frontend-inbound-icmp \
    --direction=INGRESS \
    --priority=1000 \
    --network=ccl1-network \
    --action=ALLOW \
    --rules=icmp \
    --source-ranges=0.0.0.0/0 \
    --target-service-accounts=cram-backend-service@testproject123-cram.iam.gserviceaccount.com

#firewall Rule Backend Outbound ICMP Local
gcloud compute --project=testproject123-cram firewall-rules create backend-outbound-icmp \
    --direction=EGRESS \
    --priority=1000 \
    --network=ccl1-network \ 
    --action=ALLOW \
    --rules=icmp \
    --destination-ranges=192.168.1.0/24 \
    --target-service-accounts=cram-backend-service@testproject123-cram.iam.gserviceaccount.com

#firewall Rule Backend Inbound ICMP from Frontend SA
gcloud compute --project=testproject123-cram firewall-rules create f-backend-inbound-icmp \
    --direction=INGRESS \
    --priority=1000 \
    --network=ccl1-network \
    --action=ALLOW \
    --rules=icmp \
    --source-ranges=192.168.0.0/24 \
    --target-service-accounts=cram-frontend-service@testproject123-cram.iam.gserviceaccount.com

#firewall Rule Backend Inbound ICMP from Backend SA
gcloud compute --project=testproject123-cram firewall-rules create b-backend-inbound-icmp \
    --direction=INGRESS \
    --priority=1000 \
    --network=ccl1-network \
    --action=ALLOW \
    --rules=icmp \
    --source-ranges=192.168.1.0/24 \
    --target-service-accounts=cram-backend-service@testproject123-cram.iam.gserviceaccount.com

#Create Instance Template Backend in us-west1 in backend-subnet
gcloud beta compute --project=testproject123-cram instance-templates create instance-template-backend \
    --machine-type=f1-micro \
    --subnet=projects/testproject123-cram/regions/us-west1/subnetworks/backend-subnet \
    --network-tier=PREMIUM \
    --maintenance-policy=MIGRATE \
    --service-account=cram-backend-service@testproject123-cram.iam.gserviceaccount.com \
    --scopes=https://www.googleapis.com/auth/cloud-platform \
    --region=us-west1 \
    --image=debian-10-buster-v20200618 \
    --image-project=debian-cloud \
    --boot-disk-size=10GB \
    --boot-disk-type=pd-standard \
    --boot-disk-device-name=instance-template-backend \
    --no-shielded-secure-boot \
    --no-shielded-vtpm \
    --no-shielded-integrity-monitoring \
    --reservation-affinity=any

#Create Instance Template Frontend in us-east1 in frontend-subnet
gcloud beta compute --project=testproject123-cram instance-templates create instance-template-frontend \
    --machine-type=f1-micro \
    --subnet=projects/testproject123-cram/regions/us-east1/subnetworks/frontend-subnet \
    --network-tier=PREMIUM \
    --maintenance-policy=MIGRATE \
    --service-account=cram-frontend-service@testproject123-cram.iam.gserviceaccount.com \
    --scopes=https://www.googleapis.com/auth/cloud-platform \
    --region=us-east1 \
    --image=debian-10-buster-v20200618 \
    --image-project=debian-cloud \
    --boot-disk-size=10GB \
    --boot-disk-type=pd-standard \
    --boot-disk-device-name=instance-template-frontend \
    --no-shielded-secure-boot \
    --no-shielded-vtpm \
    --no-shielded-integrity-monitoring \
    --reservation-affinity=any

#Create Instance Group Frontend in us-east1
gcloud beta compute --project=testproject123-cram instance-groups managed create frontend-instance-group \
    --base-instance-name=frontend-instance-group \
    --template=instance-template-frontend \
    --size=1 \
    --zones=us-east1-a,us-east1-b,us-east1-c \
    --instance-redistribution-type=PROACTIVE

#Create Instance Group Frontend autoscaling
gcloud beta compute --project "testproject123-cram" instance-groups managed set-autoscaling "frontend-instance-group" \
    --region "us-east1" \
    --cool-down-period "30" \
    --max-num-replicas "3" \
    --min-num-replicas "2" \
    --target-cpu-utilization "0.6" \
    --mode "on"

#Create Instance Group Backend in us-west-1
gcloud beta compute --project=testproject123-cram instance-groups managed create backend-instance-group \
    --base-instance-name=backend-instance-group \
    --template=instance-template-backend \
    --size=1 \
    --zones=us-west1-a,us-west1-b,us-west1-c \
    --instance-redistribution-type=PROACTIVE

#Create Instance Group Backend autoscaling
gcloud beta compute --project "testproject123-cram" instance-groups managed set-autoscaling "backend-instance-group" \
    --region "us-west1" \
    --cool-down-period "30" \
    --max-num-replicas "3" \
    --min-num-replicas "2" \
    --target-cpu-utilization "0.6" \
    --mode "on"

